# Generated by Django 2.2 on 2020-02-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_username', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('item_title', models.CharField(max_length=50)),
                ('item_id', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('baught_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
