# Generated by Django 2.2 on 2020-02-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_cartdetailthrough_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdetailthrough',
            name='state',
            field=models.CharField(choices=[('baught', 'baught'), ('selected', 'selected')], max_length=20),
        ),
    ]
